# Default values for deliveryfront.

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

deliveryfront:
  replicaCount: 1

  image:
    repository: registry.gitlab.com/faemproject/backend/delivery/deliveryfront
    tag: stable
    pullPolicy: IfNotPresent

  resources: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx-external
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: client.example.local
        paths: ["/"]
    tls: []
    #  - secretName: client-tls
    #    hosts:
    #      - client.example.local

  configEnvs: {}
  secretRefs: []
