# Default values for deliverycore.

nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

deliverycore:
  replicaCount: 1

  image:
    repository: registry.gitlab.com/faemproject/backend/delivery/deliverycore
    tag: stable
    pullPolicy: IfNotPresent

  resources: {}

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx-external
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: client.example.local
        paths: ["/"]
    tls: []
    #  - secretName: client-tls
    #    hosts:
    #      - client.example.local

  configEnvs: {}
  secretRefs: []
